[package]
name = "full"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx-mssql-rs = { path = "../..", version = "0.1.0", features = [
    "macros",
    "derive",
    "offline",
    "chrono",
    "uuid",
    "migrate",
] }
chrono = { version = "0.4.34", default-features = false, features = ["std", "clock"] }
futures-util = "0.3.32"
sqlx-core = { version = "0.9.0", default-features = false }
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.12.1", features = ["v7"] }
sqlx = "0.9.0"
