[package]
name = "sqlx-mssql-rs-cli"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "CLI tools for sqlx-mssql-rs."
readme = "../README.md"
keywords = ["sqlx", "mssql", "tds", "database", "cli"]
categories = ["database", "command-line-utilities"]
rust-version = "1.96"

[[bin]]
name = "cargo-sqlx-mssql"
path = "src/bin/cargo-sqlx-mssql-rs.rs"

[[bin]]
name = "sqlx-mssql"
path = "src/bin/sqlx-mssql-rs.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
console = "0.16"
sqlx-cli = "0.9.0"
sqlx-core = { version = "0.9.0", default-features = false, features = ["any", "migrate"] }
sqlx-mssql-rs-core = { version = "0.1.0", path = "../sqlx-mssql-rs-core", features = ["any", "migrate"] }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
